.TH SYNC "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
sync \- synchronize cached writes to disk storage

.SH DESCRIPTION
.B sync
[\fI\,FILE\/\fR]...

.PP
Sync cached writes to disk storage.
If one or more FILE(s) are specified, sync only them.

.SH OPTIONS
None.

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
