.TH MOUNT "8" "July 2026" "PiggyOS" "System Administration"
.SH NAME
mount \- mount a filesystem

.SH SYNOPSIS
.B mount
[\fI\,DEVICE\/\fR] \fI\,DIRECTORY\/\fR:\fI\,FSTYPE\/\fR

.SH DESCRIPTION

.PP
Mount a filesystem on DEVICE with type FSTYPE to the specified DIRECTORY.
DEVICE is optional because some filesystems (devfs, tmpfs) are not backed by a block device.

.SH OPTIONS
None.

.SH SEE ALSO
\fBunmount\fR(8)

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
