.TH YES "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
yes \- output a string repeatedly

.SH SYNOPSIS
.B yes
[\fI\,STRING\/\fR]...

.SH DESCRIPTION

.PP
Repeatedly output a line with all specified STRING(s), or 'y'.

.SH OPTIONS
None.

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
