.TH RMDIR "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
rmdir \- remove empty directories

.SH SYNOPSIS
.B rmdir
[\fI\,OPTION\/\fR]... \fI\,DIRECTORY\/\fR...

.SH DESCRIPTION

.PP
Remove the DIRECTORY(ies), if they are empty.

.PP
Why are you not just using \fBrm\fP(1)?

.SH OPTIONS

.TP
.B \-p
remove DIRECTORY and its parents

.TP
.B \-v
output a message for every directory

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
