.TH READLINK "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
readlink \- print resolved symbolic links or canonical file names

.SH SYNOPSIS
.B readlink
[\fI\,OPTION\/\fR]... \fI\,FILE\/\fR...

.SH DESCRIPTION

.PP
Print reference of a symbolic link or canonical file name.

.SH OPTIONS

.TP
.B \-f
canonicalize paths by following every symlink in every component of the path

.TP
.B \-q
supress most errors

.TP
.B \-z
line delimiter is NUL, not newline

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
