.TH PING "8" "August 2026" "PiggyOS" "System Administration"

.SH NAME
ping \- display system information with a pig-themed twist

.SH SYNOPSIS
.B ping
[\fI\,OPTION\/\fR]... \fI\,HOST\/\fR

.SH DESCRIPTION

.PP
Verify if a host is online using ICMP protocol ECHO_REQUEST datagrams.

.SH OPTIONS

.TP
.B \-a
Audible ping

.TP
.B \-c COUNT
Stop after sending COUNT packets

.TP
.B \-I INTERFACE
Bind to either the interface or address specified by INTERFACE

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
