.TH ROFF "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
roff \- format and print roff documents to the standard output

.SH SYNOPSIS
.B roff
[\fI\,FILE\/\fR]...

.SH DESCRIPTION

.PP
Interpret and print the roff document FILE to the standard output.

.PP
With no FILE, or when FILE is \-, read standard input.

.SH OPTIONS
None.

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
