.TH NOHUP "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
nohup \- run a command that is immune to hangups

.SH SYNOPSIS
.B nohup
\fI\,COMMAND\/\fR [\fI\,ARG\/\fR]...

.SH DESCRIPTION

.PP
Run COMMAND, ignoring all hangup signals.

.SH OPTIONS
None.

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
