.TH IFCONF "8" "July 2026" "PiggyOS" "System Administration"

.SH NAME
ifconf \- enumerate and edit network interfaces.

.SH SYNOPSIS
.B ifconf

.SH DESCRIPTION

.PP
Display and configure network interfaces and routing information.

.SH OPTIONS
None.

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
