.TH FACTOR "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
factor \- factor numbers

.SH SYNOPSIS
.B factor
[\fI\,OPTION\/\fR] [\fI\,NUMBER\/\fR]...

.SH DESCRIPTION

.PP
Print the prime factors of each specified integer NUMBER. If no NUMBER(s) are specified, read them
from standard input.

.SH OPTIONS
None.

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
