.TH PS "1" "August 2026" "PiggyOS" "User Commands"
.SH NAME
ps \- enumerate processes on the system

.SH SYNOPSIS
.B ps
[\fI\,OPTION\/\fR]...

.SH DESCRIPTION

.PP
Displays information about the current snapshot of processes on the system

.SH OPTIONS

.TP
.B \-p PID
only display information about process with PID, or with -t, begin process tree from PID

.TP
.B \-t
print processes as a tree

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
