.TH BASENAME "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
basename \- strip directory  from filenames

.SH SYNOPSIS
.B basename
[\fI\,OPTION\/\fR]... \fI\,NAME\/\fR...

.SH DESCRIPTION

.PP
Print each NAME with any leading directory components removed.

.SH OPTIONS

.TP
.B \-z
line delimiter is NUL, not newline

.SH SEE ALSO
\fBdirname\fR(1), \fBreadlink\fR(1)

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
