.TH HOSTNAME "1" "October 2026" "PiggyOS" "User Commands"

.SH NAME
hostname \- display or set system hostname

.SH DESCRIPTION
.B hostname
\fI\,HOSTNAME\/\fR

.PP
Display or set the system's hostname.

.SH OPTIONS
None.

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
