.TH REALPATH "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
realpath \- print resolved paths

.SH SYNOPSIS
.B realpath
[\fI\,OPTION\/\fR]... \fI\,FILE\/\fR...

.SH DESCRIPTION

.PP
Resolve the absolute filepath of each FILE and display it to standard output.

.SH OPTIONS

.TP
.B \-q
supress most errors

.TP
.B \-z
line delimiter is NUL, not newline

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
