.TH UPTIME "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
uptime \- display how long the system has been running

.SH SYNOPSIS
.B uptime
[\fI\,OPTION\/\fR]...

.SH DESCRIPTION

.PP
Prints a one line display of the following information: the current time, and how long the system has been running.

.SH OPTIONS

.TP
.B \-p
display uptime in pretty format

.TP
.B \-r
display current time and uptime in seconds

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
