.TH WHICH "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
which \- display the full path of programs

.SH SYNOPSIS
.B which
[\fI\,OPTION\/\fR]... [\fI\,NAME\/\fR]...

.SH DESCRIPTION

.PP
Search for each program NAME in the directories listed in the environment variable PATH and display them to standard output.

.SH OPTIONS

.TP
.B \-a
print all matching executables in PATH, not just the first

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
