.TH HWCLOCK "8" "July 2026" "PiggyOS" "System Administration"

.SH NAME
hwclock \- interact with hardware time clock

.SH SYNOPSIS
.B hwclock
[\fI\,OPTION\/\fR]...

.SH DESCRIPTION

.PP
Manages the hardware time clock.
If none of the options below are specified, the time on the hardware clock is display.

.SH OPTIONS

.TP
.B \-h
set the system clock from the hardware clock

.TP
.B \-s
set the hardware clock from the system clock

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
