.TH MKDIR "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
mkdir \- make directories

.SH SYNOPSIS
.B mkdir
[\fI\,OPTION\/\fR]... \fI\,DIRECTORY\/\fR...

.SH DESCRIPTION

.PP
Create the DIRECTORY(ies), if they do not already exist.

.SH OPTIONS

.TP
.B \-p
create parent directories as needed, do not error if adirectory already exists

.TP
.B \-v
output a message for every directory

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
