.TH STTY "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
stty \-  change and print terminal settings

.SH SYNOPSIS
.B stty
[\fI\,-F DEVICE\/\fR] [\fI\,SETTING\/\fR]...
[\fI\,-F DEVICE\/\fR] [\fI\,-a\/\fR]

.SH DESCRIPTION

.PP
Print or change terminal settings.

.SH OPTIONS

.TP
.B \-a
display all terminal settings

.TP
.B \-F DEVICE
open and use DEVICE instead of standard input

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
