.TH RM "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
rm \- remove files or directories

.SH SYNOPSIS
.B rm
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]...

.SH DESCRIPTION

.PP
Remove the specified FILE(s).
By default, do not remove directories.

.SH OPTIONS

.TP
.B \-f
do not prompt, ignore nonexistent files and arguments

.TP
.B \-i
prompt before every removal

.TP
.B \-r
remove directories and their contents recursively

.TP
.B \-v
display a message for each operation

.SH SEE ALSO
\fBrmdir\fR(1), \fBshred\fR(1)

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
