.TH HEXDUMP "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
hexdump \- display file contents in hexadecimal

.SH DESCRIPTION
.B hexdump
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]...

.PP
Display the contents of FILE(s) in hexadecimal format.

.PP
With no FILE, or when FILE is \-, read standard input.

.SH OPTIONS

.TP
.B \-C
output file contents in canonical hex + ASCII display mode

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
