.TH CLEAR "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
clear \- clear the terminal screen

.SH SYNOPSIS
.B clear

.SH DESCRIPTION

.PP
Clear the terminal screen.

.SH OPTIONS
None.

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
