.TH NTPD.CONF "5" "September 2026" "PiggyOS" "File Formats"

.SH NAME
ntpd.conf \- ntpd configuration file

.SH DESCRIPTION

.PP
The ntpd.conf configuration file is read at startup by ntpd(8) in order to specify synchronization servers.

.PP
The file format is similar to other \fBPiggyOS\fR configuration files. Comments begin with a '#' character and extend to the end of the line.
Blank lines are ignored.
Configuration commands consist of a keyword followed by a list of arguments seperated by whitespace.
Configuration commands can be multiline and must be terminated with a semicolon ';'.
Arguments can be text strings, or integers, or boolean truth values.
Additionally, a configuration block can be specified by a '{' after a regular command.
A configuration block may contain any number of configuration commands, and is terminated by a '}'.

.PP
Here is the list of available configuration options:

.TP
server HOST...
Specify the HOST(s) to be used as NTP syncronization servers.

.SH EXAMPLE

# Example ntpd configuration

server 0.us.pool.ntp.org 1.us.pool.ntp.org;

.SH SEE ALSO
.sp
\fBntpd\fR(8).

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
