.TH NTPD.CONF "5" "July 2026" "PiggyOS" "File Formats"

.SH NAME
ntpd.conf \- ntpd configuration file

.SH DESCRIPTION

.PP
TODO

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
