.TH MV "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
mv \- move files

.SH SYNOPSIS
.B mv
[\fI\,OPTION\/\fR]... \fI\,SOURCE\/\fR \fI\,DESTINATION\/\f
.br
.B mv
[\fI\,OPTION\/\fR]... \fI\,SOURCE\/\fR... \fI\,DIRECTORY\/\f

.SH DESCRIPTION

.PP
Rename SOURCE to DESTINATION, or move SOURCE(s) into DIRECTORY.

.SH OPTIONS

.TP
.B \-f
do not prompt before overwriting

.TP
.B \-i
prompt before overwriting

.TP
.B \-v
display a message for each operation

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
