.TH TREE "1" "August 2026" "PiggyOS" "User Commands"

.SH NAME
tree \- print contents of directories in a tree-like format

.SH SYNOPSIS
.B tree
[\fI\,OPTION\/\fR]... [\fI\,DIRECTORY\/\fR]...

.SH DESCRIPTION

.PP
Recursively print contents of directories in a depth-indented tree-like format 

.SH OPTIONS

.TP
.B \-a
do not ignore entries starting with . ('.' and '..' entries are never displayed)

.SH SEE ALSO
\fBls\fR(1)

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
