.TH DATE "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
date \- print the system date and time

.SH SYNOPSIS
.B date
[\fI\,OPTION\/\fR]... [\fB+\fR\fI\,FORMAT\/\fR]

.SH DESCRIPTION

.PP
Display date and time in the given FORMAT.

.SH OPTIONS

.TP
.B \-I
output datetime in ISO 8601 format

.TP
.B \-I
output datetime in RFC 5322 format

.TP
.B \-u
output datetime in UTC

.TP
.B \-z TZ
output datetime in timezone TZ

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
