.TH STAT "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
stat \- display file status information

.SH SYNOPSIS
.B stat
[\fI\,OPTION\/\fR]... \fI\,FILE\/\fR...

.SH DESCRIPTION

.PP
Display file status information.

.SH OPTIONS

.TP
.B \-L
dereference all symbolic links

.TP
.B \-t
print the information in terse form

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
