.TH POWEROFF "8" "April 2026" "PiggyOS" "System Administration"

.SH NAME
poweroff \- halt, reboot, or shutdown the system

.SH SYNOPSIS
.B poweroff
\fI\,OPTION\/\fR...

.SH DESCRIPTION

.PP
Perform the specified system power action.

.SH OPTIONS

.TP
.B \-h
halt the system

.TP
.B \-r
reboot the system

.TP
.B \-s
shutdown the system

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
