# Configuration file for init(8)

hostname piggy;

service hwclock {
    command /usr/bin/hwclock -h;
}

service dhcpd {
    command /usr/bin/dhcpd;
}

service ntpd {
    command /usr/bin/ntpd;
    restart failure;
    disabled;
}

service getty {
    command /usr/bin/getty /dev/tty;
    restart always;
}
