.TH PRINTF "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
printf \- format and print data

.SH SYNOPSIS
.B printf
\fI\,FORMAT\/\fR [\fI\,ARGUMENT\/\fR]...

.SH DESCRIPTION

.PP
Print ARGUMENT(s) according to FORMAT.
FORMAT controls the output as with C printf.

.SH OPTIONS
None.

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
