.TH SEQ "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
seq \- print a sequence of numbers

.SH SYNOPSIS
.B seq
[\fI\,OPTION\/\fR]... \fI\,LAST\/\fR
.br
.B seq
[\fI\,OPTION\/\fR]... \fI\,FIRST LAST\/\fR
.br
.B seq
[\fI\,OPTION\/\fR]... \fI\,FIRST INCREMENT LAST\/\fR

.SH DESCRIPTION

.PP
Print numbers from FIRST to LAST, in steps of INCREMENT.

.SH OPTIONS

.TP
.B \-s STRING
seperate numbers with STRING (default is '\en')

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
