#define _GNU_SOURCE

#include <arpa/inet.h>

#include <net/if.h>

#include <netinet/in.h>

#include <piggy/route.h>

#include <sys/ioctl.h>
#include <sys/socket.h>

#include <err.h>
#include <errno.h>
#include <poll.h>
#include <resolv.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h> 

#include <config.h>

#define BOOTREQUEST 1
#define BOOTREPLY   2

#define DHCP_DISCOVER   1
#define DHCP_OFFER      2
#define DHCP_REQUEST    3
#define DHCP_ACK        5
#define DHCP_NAK        6

#define DHCP_OPTION_SUBNET_MASK     1
#define DHCP_OPTION_ROUTER          3
#define DHCP_OPTION_DNS             6
#define DHCP_OPTION_INTERFACE_MTU   26
#define DHCP_OPTION_REQUESTED_IP    50
#define DHCP_OPTION_IP_LEASE_TIME   51
#define DHCP_OPTION_MESSAGE_TYPE    53
#define DHCP_OPTION_SERVER_ID       54
#define DHCP_OPTION_PARAM_LIST      55
#define DHCP_OPTION_RENEWAL_TIME    58
#define DHCP_OPTION_REBIND_TIME     59
#define DHCP_OPTION_END             255

#define MAGIC_COOKIE 0x63825363

#define REQUEST_DNS             (1 << 0)
#define REQUEST_INTERFACE_MTU   (1 << 1)
#define REQUEST_ROUTER          (1 << 2)
#define REQUEST_SUBNET_MASK     (1 << 3)

#define _PATH_CONFIG "/etc/dhcpd.conf"

struct dhcp_packet {
    uint8_t op;
    uint8_t htype;
    uint8_t hlen;
    uint8_t hops;

    uint32_t xid;

    uint16_t secs;
    uint16_t flags;

    uint32_t ciaddr;
    uint32_t yiaddr;
    uint32_t siaddr;
    uint32_t giaddr;

    uint8_t chaddr[16];
    uint8_t sname[64];
    uint8_t file[128];

    uint32_t magic;

    uint8_t options[312];
} __attribute__((packed));

struct dhcp_lease {
    uint32_t ip;
    uint32_t mask;
    uint32_t gateway;
    uint32_t server_id;

    uint32_t lease_seconds;
    uint32_t renewal_seconds;
    uint32_t rebind_seconds;

    uint32_t* dns;
    size_t dns_count;

    struct timespec acquired;
};

enum dhcp_state {
    STATE_SELECTING,
    STATE_REQUESTING,
    STATE_BOUND,
    STATE_RENEWING,
    STATE_REBINDING,
    STATE_FAILED,
};

struct dhcp_context {
    char interface_name[IFNAMSIZ];
    int request_options;

    size_t retries;
    size_t max_retries;

    int sockfd;
    enum dhcp_state state;

    uint8_t mac[6];
    uint32_t xid;

    struct dhcp_lease lease;
    struct dhcp_lease offer;

    struct timespec deadline;

    struct timespec renewal_deadline;
    struct timespec rebind_deadline;
    struct timespec expiry_deadline;
};

static config_t* config;

static inline struct timespec timespec_add_seconds(struct timespec ts, uint32_t seconds) {
    ts.tv_sec += seconds;
    return ts;
}

static inline bool timespec_expired(struct timespec now, struct timespec deadline) {
    return now.tv_sec > deadline.tv_sec || (now.tv_sec == deadline.tv_sec && now.tv_nsec >= deadline.tv_nsec);
}

static inline struct timespec timespec_sub(struct timespec a, struct timespec b) {
    struct timespec result = {
        .tv_sec = a.tv_sec - b.tv_sec,
        .tv_nsec = a.tv_nsec - b.tv_nsec,
    };

    if (result.tv_nsec < 0) {
        result.tv_sec--;
        result.tv_nsec += 1000000000L;
    }

    if (result.tv_sec < 0) {
        return (struct timespec) {};
    }

    return result;
}

static void send_discover(struct dhcp_context* ctx);
static void send_rebind(struct dhcp_context* ctx);
static void send_renew(struct dhcp_context* ctx);
static void send_request(struct dhcp_context* ctx);

static void apply_config(struct dhcp_context* ctx) {
    struct ifreq ifr = {};
    strncpy(ifr.ifr_name, ctx->interface_name, sizeof(ifr.ifr_name));

    ((struct sockaddr_in*) &ifr.ifr_addr)->sin_family = AF_INET;
    ((struct sockaddr_in*) &ifr.ifr_addr)->sin_addr.s_addr = ctx->lease.mask;

    if (ioctl(ctx->sockfd, SIOCSIFNETMASK, &ifr) < 0) {
        err(EXIT_FAILURE, "ioctl(SIOCSIFNETMASK)");
    }

    ((struct sockaddr_in*) &ifr.ifr_addr)->sin_family = AF_INET;
    ((struct sockaddr_in*) &ifr.ifr_addr)->sin_addr.s_addr = ctx->lease.ip;

    if (ioctl(ctx->sockfd, SIOCSIFADDR, &ifr) < 0) {
        err(EXIT_FAILURE, "ioctl(SIOCSIFADDR)");
    }

    struct rtentry rt = {};
    strncpy(rt.ifname, ctx->interface_name, sizeof(rt.ifname));

    rt.destination = 0;
    rt.gateway = ctx->lease.gateway;
    rt.mask = 0;

    if (ioctl(ctx->sockfd, SIOCADDRT, &rt) < 0) {
        err(EXIT_FAILURE, "ioctl(SIOCADDRT)");
    }

    FILE* fp = fopen(_PATH_RESCONF, "w");
    if (!fp) {
        err(EXIT_FAILURE, "fopen");
    }

    fprintf(fp, "# Generated by dhcpd\n");

    config_node_t* dns = config_find(&config->root, "domain_name_server");
    if (dns && config_value_count(dns)) {
        for (size_t i = 0; i < config_value_count(dns); i++) {
            const char* value;
            if (config_value_get_string(dns, i, &value) < 0) {
                warnx("config: failed to get domain name server value");
                continue;
            }

            struct in_addr addr;
            if (inet_pton(AF_INET, value, &addr) == 1) {
                fprintf(fp, "nameserver %s\n", value);
            } else {
                warnx("config: invalid domain name server: '%s'", value);
            }
        }
    } else {
        for (size_t i = 0; i < ctx->lease.dns_count; i++) {
            struct in_addr addr = {
                .s_addr = ctx->lease.dns[i]
            };

            fprintf(fp, "nameserver %s\n", inet_ntoa(addr));
        }
    }

    fclose(fp);
}

static void bind_lease(struct dhcp_context* ctx, struct dhcp_lease* lease) {
    free(ctx->lease.dns);

    ctx->lease = *lease;

    if (clock_gettime(CLOCK_MONOTONIC, &ctx->lease.acquired) < 0) {
        err(EXIT_FAILURE, "clock_gettime(CLOCK_MONOTONIC)");
    }

    // RFC deadline
    if (ctx->lease.renewal_seconds == 0) {
        ctx->lease.renewal_seconds = ctx->lease.lease_seconds / 2;
    }
    if (ctx->lease.rebind_seconds == 0) {
        ctx->lease.rebind_seconds = (ctx->lease.lease_seconds * 7) / 8;
    }

    ctx->renewal_deadline = timespec_add_seconds( ctx->lease.acquired, ctx->lease.renewal_seconds);
    ctx->rebind_deadline = timespec_add_seconds( ctx->lease.acquired, ctx->lease.rebind_seconds);
    ctx->expiry_deadline = timespec_add_seconds( ctx->lease.acquired, ctx->lease.lease_seconds);

    ctx->deadline = ctx->renewal_deadline;

    ctx->state = STATE_BOUND;

    apply_config(ctx);
}

static void build_pollfds(struct dhcp_context* contexts, struct pollfd* fds, size_t count) {
    for (size_t i = 0; i < count; i++) {
        fds[i] = (struct pollfd) {
            .fd = contexts[i].sockfd,
            .events = POLLIN,
            .revents = 0,
        };
    }
}

static struct timespec calculate_timeout(struct dhcp_context* contexts, size_t count) {
    struct timespec now;
    if (clock_gettime(CLOCK_MONOTONIC, &now) < 0) {
        err(EXIT_FAILURE, "clock_gettime(CLOCK_MONOTONIC)");
    }

    bool have_deadline = false;

    struct timespec earliest = {};

    for (size_t i = 0; i < count; i++) {
        struct dhcp_context* ctx = &contexts[i];
        if (ctx->state == STATE_FAILED) {
            continue;
        }

        if (!have_deadline || ctx->deadline.tv_sec < earliest.tv_sec || (ctx->deadline.tv_sec == earliest.tv_sec && ctx->deadline.tv_nsec < earliest.tv_nsec)) {
            earliest = ctx->deadline;
            have_deadline = true;
        }
    }

    if (!have_deadline) {
        return (struct timespec) { .tv_sec = 30 };
    }

    return timespec_sub(earliest, now);
}

static void process_timers(struct dhcp_context* contexts, size_t count) {
    struct timespec now;
    if (clock_gettime(CLOCK_MONOTONIC, &now) < 0) {
        err(EXIT_FAILURE, "clock_gettime(CLOCK_MONOTONIC)");
    }

    for (size_t i = 0; i < count; i++) {
        struct dhcp_context* ctx = &contexts[i];

        switch (ctx->state) {
            case STATE_SELECTING:
                if (!timespec_expired(now, ctx->deadline)) {
                    break;
                }

                if (ctx->max_retries && ctx->retries >= ctx->max_retries) {
                    ctx->state = STATE_FAILED;
                    break;
                }

                send_discover(ctx);
                ctx->retries++;

                ctx->deadline = now;
                ctx->deadline.tv_sec += 1;
                break;
            case STATE_REQUESTING:
                if (!timespec_expired(now, ctx->deadline)) {
                    break;
                }

                if (ctx->max_retries && ctx->retries >= ctx->max_retries) {
                    ctx->state = STATE_FAILED;
                    break;
                }

                send_request(ctx);
                ctx->retries++;

                ctx->deadline = now;
                ctx->deadline.tv_sec += 1;
                break;
            case STATE_BOUND:
                if (timespec_expired(now, ctx->expiry_deadline)) {
                    ctx->retries = 0;
                    ctx->state = STATE_SELECTING;
                    ctx->xid = (uint32_t) rand();

                    if (ctx->max_retries && ctx->retries >= ctx->max_retries) {
                        ctx->state = STATE_FAILED;
                        break;
                    }

                    send_discover(ctx);
                    ctx->retries++;

                    ctx->deadline = now;
                    ctx->deadline.tv_sec += 1;
                    break;
                }

                if (timespec_expired(now, ctx->renewal_deadline)) {
                    ctx->retries = 0;
                    ctx->state = STATE_RENEWING;
                    ctx->xid = (uint32_t) rand();

                    send_renew(ctx);

                    ctx->deadline = now;
                    ctx->deadline.tv_sec += 1;
                }

                break;
            case STATE_RENEWING:
                if (timespec_expired(now, ctx->expiry_deadline)) {
                    ctx->retries = 0;
                    ctx->state = STATE_SELECTING;
                    ctx->xid = (uint32_t) rand();

                    if (ctx->max_retries && ctx->retries >= ctx->max_retries) {
                        ctx->state = STATE_FAILED;
                        break;
                    }

                    send_discover(ctx);
                    ctx->retries++;

                    ctx->deadline = now;
                    ctx->deadline.tv_sec += 1;
                    break;
                }

                if (timespec_expired(now, ctx->rebind_deadline)) {
                    ctx->retries = 0;
                    ctx->state = STATE_REBINDING;
                    ctx->xid = (uint32_t) rand();

                    send_rebind(ctx);

                    ctx->deadline = now;
                    ctx->deadline.tv_sec += 1;
                    break;
                }

                if (timespec_expired(now, ctx->deadline)) {
                    if (ctx->max_retries && ctx->retries >= ctx->max_retries) {
                        ctx->state = STATE_FAILED;
                        break;
                    }

                    send_renew(ctx);
                    ctx->retries++;

                    ctx->deadline = now;
                    ctx->deadline.tv_sec += 1;
                }

                break;
            case STATE_REBINDING:
                if (timespec_expired(now, ctx->expiry_deadline)) {
                    ctx->retries = 0;
                    ctx->state = STATE_SELECTING;
                    ctx->xid = (uint32_t) rand();

                    free(ctx->lease.dns);
                    memset(&ctx->lease, 0, sizeof(ctx->lease));

                    if (ctx->max_retries && ctx->retries >= ctx->max_retries) {
                        ctx->state = STATE_FAILED;
                        break;
                    }

                    send_discover(ctx);
                    ctx->retries++;

                    ctx->deadline = now;
                    ctx->deadline.tv_sec += 1;
                    break;
                }

                if (timespec_expired(now, ctx->deadline)) {
                    if (ctx->max_retries && ctx->retries >= ctx->max_retries) {
                        ctx->state = STATE_FAILED;
                        break;
                    }

                    send_rebind(ctx);
                    ctx->retries++;

                    ctx->deadline = now;
                    ctx->deadline.tv_sec += 1;
                }

                break;
            case STATE_FAILED:
                break;
        }
    }
}

static void receive(struct dhcp_context* ctx) {
    uint8_t buf[1500];

    struct sockaddr_in from;
    socklen_t from_len = sizeof(from);

    ssize_t n = recvfrom(ctx->sockfd, buf, sizeof(buf), 0, (struct sockaddr*) &from, &from_len);
    if (n < 0) {
        warn("recvfrom(%s)", ctx->interface_name);
        return;
    }

    struct dhcp_packet* pkt = (void*) buf;
    if (pkt->op != BOOTREPLY) {
        return;
    }

    if (ntohl(pkt->xid) != ctx->xid) {
        return;
    }

    uint8_t message_type = 0;

    struct dhcp_lease lease = {};

    if (ctx->state == STATE_RENEWING || ctx->state == STATE_REBINDING) {
        lease = ctx->lease;
        lease.dns = NULL;
        lease.dns_count = 0;
    }

    uint8_t* opt = pkt->options;
    uint8_t* end = buf + n;

    while (opt < end && *opt != DHCP_OPTION_END) {
        uint8_t code = *opt++;
        if (code == 0) {
            continue;
        }

        if (code == DHCP_OPTION_END) {
            break;
        }

        uint8_t len  = *opt++;
        if (opt + len > end) {
            break;
        }

        switch (code) {
            case DHCP_OPTION_MESSAGE_TYPE:
                message_type = opt[0];
                break;
            case DHCP_OPTION_SUBNET_MASK:
                if (len == 4) {
                    memcpy(&lease.mask, opt, 4);
                }
                break;
            case DHCP_OPTION_ROUTER:
                if (len == 4) {
                    memcpy(&lease.gateway, opt, 4);
                }
                break;
            case DHCP_OPTION_IP_LEASE_TIME:
                if (len == 4) {
                    memcpy(&lease.lease_seconds, opt, 4);
                }
                lease.lease_seconds = ntohl(lease.lease_seconds);
                break;
            case DHCP_OPTION_RENEWAL_TIME:
                if (len == 4) {
                    memcpy(&lease.renewal_seconds, opt, 4);
                }
                lease.renewal_seconds = ntohl(lease.renewal_seconds);
                break;
            case DHCP_OPTION_REBIND_TIME:
                if (len == 4) {
                    memcpy(&lease.rebind_seconds, opt, 4);
                }
                lease.rebind_seconds = ntohl(lease.rebind_seconds);
                break;
            case DHCP_OPTION_DNS:
                lease.dns_count = len / 4;

                lease.dns = malloc(lease.dns_count * sizeof(uint32_t));
                if (!lease.dns) {
                    errx(EXIT_FAILURE, "malloc");
                }

                memcpy(lease.dns, opt, lease.dns_count * sizeof(uint32_t));
                break;
            case DHCP_OPTION_SERVER_ID:
                if (len == 4) {
                    memcpy(&lease.server_id, opt, 4);
                }
                break;
        }

        opt += len;
    }

    lease.ip = pkt->yiaddr;

    if (message_type == DHCP_OFFER && ctx->state == STATE_SELECTING) {
        ctx->offer = lease;
        ctx->state = STATE_REQUESTING;

        send_request(ctx);

        struct timespec now;
        if (clock_gettime(CLOCK_MONOTONIC, &now) < 0) {
            err(EXIT_FAILURE, "clock_gettime(CLOCK_MONOTONIC)");
        }

        ctx->deadline = now;
        ctx->deadline.tv_sec += 1;
        return;
    }

    if (message_type == DHCP_ACK && (ctx->state == STATE_REQUESTING || ctx->state == STATE_RENEWING || ctx->state == STATE_REBINDING)) {
        bind_lease(ctx, &lease);
        return;
    }

    if (message_type == DHCP_NAK) {
        ctx->state = STATE_SELECTING;
    }
}

static void send_discover(struct dhcp_context* ctx) {
    struct dhcp_packet discover = {};

    discover.op = BOOTREQUEST;
    discover.htype = 1;
    discover.hlen = 6;
    discover.xid = htonl(ctx->xid);
    discover.flags = htons(0x8000);
    discover.magic = htonl(MAGIC_COOKIE);

    memcpy(discover.chaddr, ctx->mac, 6);

    uint8_t* opt = discover.options;

    *opt++ = DHCP_OPTION_MESSAGE_TYPE;
    *opt++ = 1;
    *opt++ = DHCP_DISCOVER;

    if (ctx->request_options != 0) {
        *opt++ = DHCP_OPTION_PARAM_LIST;

        uint8_t* len = opt++;

        if (ctx->request_options & REQUEST_DNS) {
            *len += 1;
            *opt++ = DHCP_OPTION_DNS;
        }

        if (ctx->request_options & REQUEST_INTERFACE_MTU) {
            *len += 1;
            *opt++ = DHCP_OPTION_INTERFACE_MTU;
        }

        if (ctx->request_options & REQUEST_ROUTER) {
            *len += 1;
            *opt++ = DHCP_OPTION_ROUTER;
        }

        if (ctx->request_options & REQUEST_SUBNET_MASK) {
            *len += 1;
            *opt++ = DHCP_OPTION_SUBNET_MASK;
        }
    }

    *opt++ = DHCP_OPTION_END;

    size_t len = sizeof(discover) - sizeof(discover.options) + (opt - discover.options);

    struct sockaddr_in dest = {
        .sin_family = AF_INET,
        .sin_port = htons(67),
        .sin_addr.s_addr = INADDR_BROADCAST,
    };

    if (sendto(ctx->sockfd, &discover, len, 0, (struct sockaddr*) &dest, sizeof(dest)) < 0) {
        err(EXIT_FAILURE, "sendto");
    }
}

static void send_rebind(struct dhcp_context* ctx) {
    struct dhcp_packet request = {};

    request.op = BOOTREQUEST;
    request.htype = 1;
    request.hlen = 6;
    request.xid = htonl(ctx->xid);
    request.ciaddr = ctx->lease.ip;
    request.magic = htonl(MAGIC_COOKIE);

    memcpy(request.chaddr, ctx->mac, 6);

    uint8_t* opt = request.options;

    *opt++ = DHCP_OPTION_MESSAGE_TYPE;
    *opt++ = 1;
    *opt++ = DHCP_REQUEST;

    *opt++ = DHCP_OPTION_END;

    size_t len = sizeof(request) - sizeof(request.options) + (opt - request.options);

    struct sockaddr_in dest = {
        .sin_family = AF_INET,
        .sin_port = htons(67),
        .sin_addr.s_addr = INADDR_BROADCAST,
    };

    if (sendto(ctx->sockfd, &request, len, 0, (struct sockaddr*) &dest, sizeof(dest)) < 0) {
        err(EXIT_FAILURE, "sendto");
    }
}

static void send_renew(struct dhcp_context* ctx) {
    struct dhcp_packet request = {};

    request.op = BOOTREQUEST;
    request.htype = 1;
    request.hlen = 6;
    request.xid = htonl(ctx->xid);
    request.ciaddr = ctx->lease.ip;
    request.magic = htonl(MAGIC_COOKIE);

    memcpy(request.chaddr, ctx->mac, 6);

    uint8_t* opt = request.options;

    *opt++ = DHCP_OPTION_MESSAGE_TYPE;
    *opt++ = 1;
    *opt++ = DHCP_REQUEST;

    *opt++ = DHCP_OPTION_END;

    size_t len = sizeof(request) - sizeof(request.options) + (opt - request.options);

    struct sockaddr_in dest = {
        .sin_family = AF_INET,
        .sin_port = htons(67),
        .sin_addr.s_addr = ctx->lease.server_id,
    };

    if (sendto(ctx->sockfd, &request, len, 0, (struct sockaddr*) &dest, sizeof(dest)) < 0) {
        err(EXIT_FAILURE, "sendto");
    }
}

static void send_request(struct dhcp_context* ctx) {
    struct dhcp_packet request = {};

    request.op = BOOTREQUEST;
    request.htype = 1;
    request.hlen = 6;
    request.xid = htonl(ctx->xid);
    request.flags = htons(0x8000);
    request.magic = htonl(MAGIC_COOKIE);

    memcpy(request.chaddr, ctx->mac, 6);

    uint8_t* opt = request.options;

    *opt++ = DHCP_OPTION_MESSAGE_TYPE;
    *opt++ = 1;
    *opt++ = DHCP_REQUEST;

    *opt++ = DHCP_OPTION_REQUESTED_IP;
    *opt++ = 4;
    memcpy(opt, &ctx->offer.ip, 4);
    opt += 4;

    *opt++ = DHCP_OPTION_SERVER_ID;
    *opt++ = 4;
    memcpy(opt, &ctx->offer.server_id, 4);
    opt += 4;

    *opt++ = DHCP_OPTION_END;

    size_t len  = sizeof(request) - sizeof(request.options) + (opt - request.options);

    struct sockaddr_in dest = {
        .sin_family = AF_INET,
        .sin_port = htons(67),
        .sin_addr.s_addr = INADDR_BROADCAST,
    };

    if (sendto(ctx->sockfd, &request, len, 0, (struct sockaddr*) &dest, sizeof(dest)) < 0) {
        err(EXIT_FAILURE, "sendto");
    }
}

static void usage(void) {
    fprintf(stderr, "usage: dhcpd [-c CONFIG]\n");
    exit(EXIT_FAILURE);
}

int main(int argc, char* argv[]) {
    const char* config_path = _PATH_CONFIG;

    int c;
    while ((c = getopt(argc, argv, "c:")) != -1) {
        switch (c) {
            case 'c':
                config_path = optarg;
                break;
            default:
                usage();
        }
    }

    argc -= optind;
    argv += optind;

    if (argc > 0) {
        warnx("extra operands provided");
        usage();
    }

    srand(time(NULL) ^ getpid());

    config = config_load_from_file(config_path);
    if (!config) {
        errx(EXIT_FAILURE, "failed to load config");
    }

    size_t capacity = 2;
    size_t interface_count = 0;

    struct dhcp_context* contexts = malloc(sizeof(struct dhcp_context) * capacity);
    if (!contexts) {
        errx(EXIT_FAILURE, "malloc");
    }

    config_iterator_t iter;
    config_iterator_init(&iter, &config->root, "interface");

    config_node_t* interface;
    while ((interface = config_iterator_next(&iter))) {
        const char* interface_name;
        if (config_value_get_string(interface, 0, &interface_name) < 0) {
            warnx("config: missing interface name");
            continue;
        }

        if (interface_count == capacity) {
            capacity *= 2;
            contexts = reallocarray(contexts, capacity, sizeof(struct dhcp_context));
            if (!contexts) {
                err(EXIT_FAILURE, "reallocarray");
            }
        }

        struct dhcp_context* ctx = &contexts[interface_count++];
        memset(ctx, 0, sizeof(struct dhcp_context));

        strncpy(ctx->interface_name, interface_name, sizeof(ctx->interface_name));
        ctx->interface_name[IFNAMSIZ - 1] = '\0';

        config_node_t* request = config_find(interface, "request");
        if (request && config_value_count(request)) {
            for (size_t i = 0; i < config_value_count(request); i++) {
                const char* value;
                if (config_value_get_string(request, i, &value) < 0) {
                    continue;
                }

                if (strcmp(value, "dns") == 0) {
                    ctx->request_options |= REQUEST_DNS;
                } else if (strcmp(value, "mtu") == 0) {
                    ctx->request_options |= REQUEST_INTERFACE_MTU;
                } else if (strcmp(value, "routers") == 0) {
                    ctx->request_options |= REQUEST_ROUTER;
                } else if (strcmp(value, "subnet-mask") == 0) {
                    ctx->request_options |= REQUEST_SUBNET_MASK;
                }
            }
        }

        config_node_t* retries = config_find(interface, "retry");

        long value;
        if (config_value_get_int(retries, 0, &value) < 0) {
            warnx("config: failed to parse retry value");
        }

        if (value <= 0) {
            warnx("config: invalid retry value: %ld", value);
        }

        ctx->max_retries = (size_t) value;

        ctx->sockfd = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
        if (ctx->sockfd < 0) {
            err(EXIT_FAILURE, "socket");
        }

        struct ifreq ifr = {};
        strcpy(ifr.ifr_name, ctx->interface_name);

        if (ioctl(ctx->sockfd, SIOCIFBIND, &ifr) < 0) {
            err(EXIT_FAILURE, "ioctl(SIOCIFBIND)");
        }

        if (ioctl(ctx->sockfd, SIOCGIFHWADDR, &ifr) < 0) {
            err(EXIT_FAILURE, "ioctl(SIOCGIFHWADDR)");
        }

        memcpy(ctx->mac, (uint8_t*) ifr.ifr_hwaddr.sa_data, 6);

        struct sockaddr_in local = {
            .sin_family = AF_INET,
            .sin_port = htons(68),
            .sin_addr.s_addr = INADDR_ANY,
        };

        if (bind(ctx->sockfd, (struct sockaddr*) &local, sizeof(local)) < 0) {
            err(EXIT_FAILURE, "bind");
        }

        ctx->xid = rand();
        ctx->state = STATE_SELECTING;
    }

    config_free(config);

    struct pollfd* fds = malloc(sizeof(struct pollfd) * interface_count);
    if (!fds) {
        errx(EXIT_FAILURE, "malloc");
    }

    for (size_t i = 0; i < interface_count; i++) {
        struct dhcp_context* ctx = &contexts[i];

        printf("%s discover\n", ctx->interface_name);
        send_discover(ctx);

        struct timespec now;
        if (clock_gettime(CLOCK_MONOTONIC, &now) < 0) {
            err(EXIT_FAILURE, "clock_gettime(CLOCK_MONOTONIC)");
        }

        ctx->deadline = now;
        ctx->deadline.tv_sec += 1;
    }

    for (;;) {
        build_pollfds(contexts, fds, interface_count);

        struct timespec timeout = calculate_timeout(contexts, interface_count);

        int ret = ppoll(fds, interface_count, &timeout, NULL);
        if (ret < 0) {
            if (errno == EINTR) {
                continue;
            }

            err(EXIT_FAILURE, "ppoll");
        }

        for (size_t i = 0; i < interface_count; i++) {
            if (!(fds[i].revents & POLLIN)) {
                continue;
            }

            receive(&contexts[i]);
        }

        process_timers(contexts, interface_count);
    }

    free(fds);
    free(contexts);

    return EXIT_SUCCESS;
}
