.TH DHCPD "8" "September 2026" "PiggyOS" "System Administration"

.SH NAME
dhcpd \- system DHCP client

.SH SYNOPSIS
.B dhpcd
[\fI\,OPTION\/\fR]...

.SH DESCRIPTION

.PP
Operating system daemon that implements a DHCP client.

.SH OPTIONS

.TP
.B \-c CONFIG
load a configuration file from path CONFIG instead of the default /etc/dhcpd.conf

.SH FILES

.TS
\fB/etc/dhcpd.conf\fR default configuration file
.TE

.SH SEE ALSO
\fBdhcpd.conf\fR(5)

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
