#include <arpa/inet.h>

#include <net/if.h>

#include <netinet/in.h>

#include <piggy/route.h>

#include <sys/ioctl.h>
#include <sys/socket.h>

#include <err.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h> 

#include <config.h>

#define BOOTREQUEST 1
#define BOOTREPLY   2

#define DHCP_DISCOVER   1
#define DHCP_OFFER      2
#define DHCP_REQUEST    3
#define DHCP_ACK        5
#define DHCP_NAK        6

#define DHCP_OPTION_SUBNET_MASK     1
#define DHCP_OPTION_ROUTER          3
#define DHCP_OPTION_DNS             6
#define DHCP_OPTION_INTERFACE_MTU   26
#define DHCP_OPTION_REQUESTED_IP    50
#define DHCP_OPTION_IP_LEASE_TIME   51
#define DHCP_OPTION_MESSAGE_TYPE    53
#define DHCP_OPTION_SERVER_ID       54
#define DHCP_OPTION_PARAM_LIST      55
#define DHCP_OPTION_REBIND_TIME     59
#define DHCP_OPTION_RENEWAL_TIME    58
#define DHCP_OPTION_END             255

#define MAGIC_COOKIE 0x63825363

#define REQUEST_DNS             (1 << 0)
#define REQUEST_INTERFACE_MTU   (1 << 1)
#define REQUEST_ROUTER          (1 << 2)
#define REQUEST_SUBNET_MASK     (1 << 3)

#define _PATH_CONFIG "/etc/dhcpd.conf"

struct dhcp_packet {
    uint8_t op;
    uint8_t htype;
    uint8_t hlen;
    uint8_t hops;

    uint32_t xid;

    uint16_t secs;
    uint16_t flags;

    uint32_t ciaddr;
    uint32_t yiaddr;
    uint32_t siaddr;
    uint32_t giaddr;

    uint8_t chaddr[16];
    uint8_t sname[64];
    uint8_t file[128];

    uint32_t magic;

    uint8_t options[312];
} __attribute__((packed));

struct dhcp_lease {
    uint32_t ip;
    uint32_t mask;
    uint32_t gateway;
    uint32_t server_id;

    time_t lease_time;
    time_t renewal_time;

    uint32_t* dns;
    size_t dns_count;
};

enum dhcp_state {
    STATE_SELECTING,
    STATE_REQUESTING,
    STATE_BOUND,
    STATE_FAILED,
};

struct dhcp_context {
    char interface_name[IFNAMSIZ];
    int request_options;

    int sockfd;
    enum dhcp_state state;
    size_t retries;
    size_t max_retries;

    uint8_t mac[6];
    uint32_t xid;

    struct dhcp_lease lease;
    struct dhcp_lease offer;

    struct dhcp_context* next;
};

static config_t* config;
static struct dhcp_context* context_list;

static void apply_config(struct dhcp_context* ctx) {
    struct ifreq ifr = {};
    strncpy(ifr.ifr_name, ctx->interface_name, sizeof(ifr.ifr_name));

    ((struct sockaddr_in*) &ifr.ifr_addr)->sin_family = AF_INET;
    ((struct sockaddr_in*) &ifr.ifr_addr)->sin_addr.s_addr = ctx->lease.mask;

    if (ioctl(ctx->sockfd, SIOCSIFNETMASK, &ifr) < 0) {
        err(EXIT_FAILURE, "ioctl(SIOCSIFNETMASK)");
    }

    ((struct sockaddr_in*) &ifr.ifr_addr)->sin_family = AF_INET;
    ((struct sockaddr_in*) &ifr.ifr_addr)->sin_addr.s_addr = ctx->lease.ip;

    if (ioctl(ctx->sockfd, SIOCSIFADDR, &ifr) < 0) {
        err(EXIT_FAILURE, "ioctl(SIOCSIFADDR)");
    }

    struct rtentry rt = {};
    strncpy(rt.ifname, ctx->interface_name, sizeof(rt.ifname));

    rt.destination = 0;
    rt.gateway = ctx->lease.gateway;
    rt.mask = 0;

    if (ioctl(ctx->sockfd, SIOCADDRT, &rt) < 0) {
        err(EXIT_FAILURE, "ioctl(SIOCADDRT)");
    }

    FILE* fp = fopen("/etc/resolv.conf", "w");
    if (!fp) {
        err(EXIT_FAILURE, "fopen");
    }

    fprintf(fp, "# Generated by dhcpd\n");

    config_node_t* dns = config_find(&config->root, "domain_name_server");
    if (dns && config_value_count(dns)) {
        for (size_t i = 0; i < config_value_count(dns); i++) {
            const char* value;
            if (config_value_get_string(dns, i, &value) < 0) {
                warnx("config: failed to get domain name server value");
                continue;
            }

            struct in_addr addr;
            if (inet_pton(AF_INET, value, &addr) == 1) {
                fprintf(fp, "nameserver %s\n", value);
            } else {
                warnx("config: invalid domain name server: '%s'", value);
            }
        }
    } else {
        for (size_t i = 0; i < ctx->lease.dns_count; i++) {
            struct in_addr addr = {
                .s_addr = ctx->lease.dns[i]
            };

            fprintf(fp, "nameserver %s\n", inet_ntoa(addr));
        }
    }

    fclose(fp);
}

static void send_discover(struct dhcp_context* ctx) {
    struct dhcp_packet discover = {};

    discover.op = BOOTREQUEST;
    discover.htype = 1;
    discover.hlen = 6;
    discover.xid = htonl(ctx->xid);
    discover.flags = htons(0x8000);
    discover.magic = htonl(MAGIC_COOKIE);

    memcpy(discover.chaddr, ctx->mac, 6);

    uint8_t* opt = discover.options;

    *opt++ = DHCP_OPTION_MESSAGE_TYPE;
    *opt++ = 1;
    *opt++ = DHCP_DISCOVER;

    if (ctx->request_options != 0) {
        *opt++ = DHCP_OPTION_PARAM_LIST;

        uint8_t* len = opt++;

        if (ctx->request_options & REQUEST_DNS) {
            *len += 1;
            *opt++ = DHCP_OPTION_DNS;
        }

        if (ctx->request_options & REQUEST_INTERFACE_MTU) {
            *len += 1;
            *opt++ = DHCP_OPTION_INTERFACE_MTU;
        }

        if (ctx->request_options & REQUEST_ROUTER) {
            *len += 1;
            *opt++ = DHCP_OPTION_ROUTER;
        }

        if (ctx->request_options & REQUEST_SUBNET_MASK) {
            *len += 1;
            *opt++ = DHCP_OPTION_SUBNET_MASK;
        }
    }

    *opt++ = DHCP_OPTION_END;

    size_t len  = sizeof(discover) - sizeof(discover.options) + (opt - discover.options);

    struct sockaddr_in dest = {
        .sin_family = AF_INET,
        .sin_port = htons(67),
        .sin_addr.s_addr = INADDR_BROADCAST,
    };

    if (sendto(ctx->sockfd, &discover, len, 0, (struct sockaddr*) &dest, sizeof(dest)) < 0) {
        err(EXIT_FAILURE, "sendto");
    }
}

static void send_request(struct dhcp_context* ctx) {
    struct dhcp_packet request = {};

    request.op = BOOTREQUEST;
    request.htype = 1;
    request.hlen = 6;
    request.xid = htonl(ctx->xid);
    request.flags = htons(0x8000);
    request.magic = htonl(MAGIC_COOKIE);

    memcpy(request.chaddr, ctx->mac, 6);

    uint8_t* opt = request.options;

    *opt++ = DHCP_OPTION_MESSAGE_TYPE;
    *opt++ = 1;
    *opt++ = DHCP_REQUEST;

    *opt++ = DHCP_OPTION_REQUESTED_IP;
    *opt++ = 4;
    memcpy(opt, &ctx->offer.ip, 4);
    opt += 4;

    *opt++ = DHCP_OPTION_SERVER_ID;
    *opt++ = 4;
    memcpy(opt, &ctx->offer.server_id, 4);
    opt += 4;

    *opt++ = DHCP_OPTION_END;

    size_t len  = sizeof(request) - sizeof(request.options) + (opt - request.options);

    struct sockaddr_in dest = {
        .sin_family = AF_INET,
        .sin_port = htons(67),
        .sin_addr.s_addr = INADDR_BROADCAST,
    };

    if (sendto(ctx->sockfd, &request, len, 0, (struct sockaddr*) &dest, sizeof(dest)) < 0) {
        err(EXIT_FAILURE, "sendto");
    }
}

static void usage(void) {
    fprintf(stderr, "usage: dhcpd [-c CONFIG]\n");
    exit(EXIT_FAILURE);
}

int main(int argc, char* argv[]) {
    const char* config_path = _PATH_CONFIG;

    int c;
    while ((c = getopt(argc, argv, "c:")) != -1) {
        switch (c) {
            case 'c':
                config_path = optarg;
                break;
            default:
                usage();
        }
    }

    argc -= optind;
    argv += optind;

    if (argc > 0) {
        warnx("extra operands provided");
        usage();
    }

    srand(time(NULL) ^ getpid());

    config = config_load_from_file(config_path);
    if (!config) {
        errx(EXIT_FAILURE, "failed to load config");
    }

    config_iterator_t iter;
    config_iterator_init(&iter, &config->root, "interface");

    config_node_t* interface;
    while ((interface = config_iterator_next(&iter))) {
        struct dhcp_context* ctx = calloc(1, sizeof(struct dhcp_context));
        if (!ctx) {
            err(EXIT_FAILURE, "calloc");
        }

        const char* interface_name;
        if (config_value_get_string(interface, 0, &interface_name) < 0) {
            warnx("config: missing interface name");
            continue;
        }
        strncpy(ctx->interface_name, interface_name, sizeof(ctx->interface_name));
        ctx->interface_name[IFNAMSIZ - 1] = '\0';

        config_node_t* request = config_find(interface, "request");
        if (request && config_value_count(request)) {
            for (size_t i = 0; i < config_value_count(request); i++) {
                const char* value;
                if (config_value_get_string(request, i, &value) < 0) {
                    continue;
                }

                if (strcmp(value, "dns") == 0) {
                    ctx->request_options |= REQUEST_DNS;
                } else if (strcmp(value, "mtu") == 0) {
                    ctx->request_options |= REQUEST_INTERFACE_MTU;
                } else if (strcmp(value, "routers") == 0) {
                    ctx->request_options |= REQUEST_ROUTER;
                } else if (strcmp(value, "subnet-mask") == 0) {
                    ctx->request_options |= REQUEST_SUBNET_MASK;
                }
            }
        }

        config_node_t* retries = config_find(interface, "retry");

        long value;
        if (config_value_get_int(retries, 0, &value) < 0) {
            warnx("config: failed to parse retry value");
        }

        if (value < 0) {
            warnx("config: invalid retry value: %ld", value);
        }

        ctx->max_retries = (size_t) value;

        ctx->sockfd = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
        if (ctx->sockfd < 0) {
            err(EXIT_FAILURE, "socket");
        }

        struct ifreq ifr = {};
        strcpy(ifr.ifr_name, ctx->interface_name);

        if (ioctl(ctx->sockfd, SIOCIFBIND, &ifr) < 0) {
            err(EXIT_FAILURE, "ioctl(SIOCIFBIND)");
        }

        if (ioctl(ctx->sockfd, SIOCGIFHWADDR, &ifr) < 0) {
            err(EXIT_FAILURE, "ioctl(SIOCGIFHWADDR)");
        }

        memcpy(ctx->mac, (uint8_t*) ifr.ifr_hwaddr.sa_data, 6);

        struct sockaddr_in local = {
            .sin_family = AF_INET,
            .sin_port = htons(68),
            .sin_addr.s_addr = INADDR_ANY,
        };

        if (bind(ctx->sockfd, (struct sockaddr*) &local, sizeof(local)) < 0) {
            err(EXIT_FAILURE, "bind");
        }

        ctx->xid = rand();

        ctx->state = STATE_SELECTING;

        ctx->next = context_list;
        context_list = ctx;
    }

    struct dhcp_context* ctx = context_list;
    while (ctx) {
        for (;;) {
            if (ctx->max_retries != 0 && ctx->retries > ctx->max_retries) {
                break;
            }

            if (ctx->state == STATE_SELECTING) {
                send_discover(ctx);
            } else if (ctx->state == STATE_REQUESTING) {
                send_request(ctx);
            }

            uint8_t buf[1500];

            struct sockaddr_in from;
            socklen_t from_len = sizeof(from);

            ssize_t n = recvfrom(ctx->sockfd, buf, sizeof(buf), 0, (struct sockaddr*) &from, &from_len);
            if (n < 0) {
                ctx->retries++;
                continue;
            }

            struct dhcp_packet* pkt = (void*) buf;
            if (pkt->op != BOOTREPLY) {
                ctx->retries++;
                continue;
            }
            if (ntohl(pkt->xid) != ctx->xid) {
                ctx->retries++;
                continue;
            }

            uint8_t message_type = 0;
            struct dhcp_lease lease = {};

            uint8_t* opt = pkt->options;
            uint8_t* end = buf + n;

            while (opt < end && *opt != DHCP_OPTION_END) {
                uint8_t code = *opt++;
                uint8_t len  = *opt++;

                if (opt + len > end) {
                    break;
                }

                switch (code) {
                    case DHCP_OPTION_MESSAGE_TYPE:
                        message_type = opt[0];
                        break;
                    case DHCP_OPTION_SUBNET_MASK:
                        memcpy(&lease.mask, opt, 4);
                        break;
                    case DHCP_OPTION_ROUTER:
                        memcpy(&lease.gateway, opt, 4);
                        break;
                    case DHCP_OPTION_DNS:
                        lease.dns_count = len / 4;

                        lease.dns = malloc(lease.dns_count * sizeof(uint32_t));
                        if (!lease.dns) {
                            errx(EXIT_FAILURE, "malloc");
                        }

                        memcpy(lease.dns, opt, lease.dns_count * sizeof(uint32_t));
                        break;
                    case DHCP_OPTION_SERVER_ID:
                        memcpy(&lease.server_id, opt, 4);
                        break;
                }

                opt += len;
            }

            lease.ip = pkt->yiaddr;

            if (message_type == DHCP_OFFER && ctx->state == STATE_SELECTING) {
                ctx->offer = lease;
                ctx->state = STATE_REQUESTING;
            }

            if (message_type == DHCP_ACK && ctx->state == STATE_REQUESTING) {
                ctx->lease = lease;
                ctx->state = STATE_BOUND;

                apply_config(ctx);
                break;
            }

            if (message_type == DHCP_NAK) {
                ctx->state = STATE_SELECTING;
                ctx->retries++;
            }
        }

        close(ctx->sockfd);

        ctx = ctx->next;
    }

    config_free(config);

    return EXIT_SUCCESS;
}
