.TH DIRNAME "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
dirname \- strip last component from filenames

.SH SYNOPSIS
.B dirname
[\fI\,OPTION\/\fR]... \fI\,NAME\/\fR...

.SH DESCRIPTION

.PP
Print the directory component of each NAME.
If NAME contains no slashes, output '.' to indicate the current directory.

.SH OPTIONS

.TP
.B \-z
line delimiter is NUL, not newline

.SH SEE ALSO
\fBbasename\fR(1), \fBreadlink\fR(1)

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
