.TH INIT "8" "July 2026" "PiggyOS" "System Administration"

.SH NAME
init \- initializes the system

.SH SYNOPSIS
.B init

.SH DESCRIPTION

.PP
First userspace process run (PID=1), started directly by the kernel.
Runs /etc/rc, and starts an interactive shell.

.SH OPTIONS
None.

.SH FILES

.TS
\fB/etc/rc.conf\fR configuration file
.TE

.SH SEE ALSO
\fBrc.conf\fR(5)

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
