.TH BASE64 "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
base64 \- base64 encode or decode data and print it to standard output

.SH SYNOPSIS
.B base64
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]

.SH DESCRIPTION

.PP
Base64 encode or decode FILE, or standard input, and print it to standard output.

.PP
With no FILE, or when FILE is \-, read standard input.

.SH OPTIONS

.TP
.B \-d
decode data

.SH SEE ALSO
\fBbase32\fR(1)

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
