.TH TTY "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
tty \- print the file name of the current terminal

.SH SYNOPSIS
.B tty
[\fI\,OPTION\/\fR]...

.SH DESCRIPTION

.PP
Print the file name of the terminal currently connected to standard input.

.SH OPTIONS

.TP
.B \-s
print nothing

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
