.TH SH "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
sh \- shell command interpreter

.SH SYNOPSIS
.B sh
[\fI\,OPTION\/\fR]... [\fI\,COMMAND\/\fR]...
.br
.B sh
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]

.SH DESCRIPTION

.PP
The shell is command interpreter that reads and executes commands from either COMMAND arguments, a FILE, or standard input.

.SH OPTIONS

.TP
.B \-c
any COMMAND(s) are executed by the shell

.TP
.B \-i
the shell is interactive

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
