.TH XARGS "1" "August 2026" "PiggyOS" "User Commands"

.SH NAME
xargs \- build and execute command lines from standard input

.SH SYNOPSIS
.B xargs
[\fI\,OPTION\/\fR]... [\fI\,COMMAND\/\fR]

.SH DESCRIPTION

.PP
Repeatedly output a line with all specified STRING(s), or 'y'.

.SH OPTIONS

.TP
.B \-0
argument delimiter is NUL, not newline

.TP
.B \-n NUM
limit the maximum arguments per command line to NUM

.TP
.B \-v
print the command before executing

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
