.TH VIP "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
vip \- text editor

.SH SYNOPSIS
.B vip
[\fI\,FILE\/\fR]...

.SH DESCRIPTION

.PP
A simple, Vi-like text editor.
Vi but Piggy.
No more questions please.

.SH OPTIONS
None.

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
