.TH UNMOUNT "8" "July 2026" "PiggyOS" "System Administration"

.SH NAME
unmount \- unmount a filesystem

.SH SYNOPSIS
.B unmount
\fI\,DIRECTORY\/\fR

.SH DESCRIPTION

.PP
Unmount a filesystem from the file hierarchy.
Filesystems are specified by the directory where they are mounted.

.SH OPTIONS
None.

.SH SEE ALSO
\fBmount\fR(8)

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
