.TH MAN "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
man \- read or list system reference manuals

.SH SYNOPSIS
.B man
[\fI\,SECTION\/\fR] \fI\,PAGE\/\fR
.br
.B man
-l \fI\,FILE\/\fR

.SH DESCRIPTION

.PP
Read a system reference manual PAGE in section SECTION.

.PP
With no SECTION, all available manual sections are searched.

.SH OPTIONS

.TP
.B \-l
resolve FILE as the path to a local roff document

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
