.TH TRUE "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
true \- do nothing, successfully

.SH SYNOPSIS
.B true

.SH DESCRIPTION

.PP
Exit with a status code indicating success.

.SH OPTIONS
None.

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
