.TH BASE32 "1" "April 2026" "PiggyOS" "User Commands"

.SH NAME
base32 \- base32 encode or decode data and print it to standard output

.SH SYNOPSIS
.B base32
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]

.SH DESCRIPTION

.PP
Base32 encode or decode FILE, or standard input, and print it to standard output.

.PP
With no FILE, or when FILE is \-, read standard input.

.SH OPTIONS

.TP
.B \-d
decode data

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
