.TH TEE "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
tee \- read from standard input and write to standard output and files

.SH SYNOPSIS
.B tee
[\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]...

.SH DESCRIPTION

.PP
Copy standard input to each FILE, and also to standard output.

.SH OPTIONS

.TP
.B \-a
append to each FILE, do not overwrite

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
