.TH PWD "1" "July 2026" "PiggyOS" "User Commands"

.SH NAME
pwd \- print name of current directory

.SH SYNOPSIS
.B pwd
[\fI\,OPTION\/\fR]...

.SH DESCRIPTION

.PP
Print the current working directory.

.SH OPTIONS

.TP
.B \-L
try to use PWD environment variable, do -P behavior if it fails

.TP
.B \-P
resolve all symlinks

.SH AUTHOR
Written by nimrod.

.SH BUGS
Report bugs to: <https://github.com/ImaNimrod/piggy-os/issues/>.

.SH COPYRIGHT
Copyright \(co 2026 nimrod
License MIT: The MIT License <https://mit-license.org/>.
