project(
  'userspace',
  'c',
  default_options: ['c_std=gnu23', 'optimization=2', 'warning_level=2'],
)

subdir('shared')

subdir('lib')

subdir('base32')
subdir('base64')
subdir('basename')
subdir('cal')
subdir('cat')
subdir('chroot')
subdir('clear')
subdir('cp')
subdir('date')
subdir('dhcpd')
subdir('dirname')
subdir('echo')
subdir('env')
subdir('expr')
subdir('factor')
subdir('false')
subdir('head')
subdir('hexdump')
subdir('hwclock')
subdir('init')
subdir('kill')
subdir('ln')
subdir('ls')
subdir('man')
subdir('mkdir')
subdir('mktemp')
subdir('more')
subdir('mount')
subdir('mv')
subdir('nohup')
subdir('ntpd')
subdir('pigfetch')
subdir('ping')
subdir('printf')
subdir('ps')
subdir('pwd')
subdir('readlink')
subdir('realpath')
subdir('rm')
subdir('rmdir')
subdir('roff')
subdir('seq')
subdir('sh')
subdir('shred')
subdir('shuf')
subdir('sleep')
subdir('stat')
subdir('stty')
subdir('sync')
subdir('tail')
subdir('tee')
subdir('touch')
subdir('true')
subdir('truncate')
subdir('tty')
subdir('uname')
subdir('uniq')
subdir('unmount')
subdir('uptime')
subdir('vip')
subdir('wc')
subdir('which')
subdir('yes')
